[package]
name = "gat"
version = "0.1.0"
edition = "2024"
authors = ["Jack Roddy <jack.w.roddy@gmail.com>"]
repository = "https://github.com/jackroddy/gat"
license = "MIT OR Apache-2.0"
description = "graphics at terminal"

[dependencies]
lexopt = "0.3"
base64 = "0.23"
flate2 = { version = "1.1", default-features = false, features = ["rust_backend"] }
rustix = { version = "1.1", features = ["termios", "stdio", "event"] }
image = { version = "0.25", default-features = false }
hayro = { version = "0.7", optional = true }
resvg = { version = "0.48", optional = true, default-features = false }
pdfium-render = { version = "0.9", optional = true, default-features = false, features = ["image_025", "thread_safe", "pdfium_latest"] }
pulldown-cmark = { version = "0.13", optional = true, default-features = false }
unicode-width = { version = "0.2", optional = true }

[features]
default = ["png", "jpeg", "pdf", "svg", "markdown"]
png = ["image/png"]
jpeg = ["image/jpeg"]
svg = ["dep:resvg", "resvg/text"]
pdf = ["dep:hayro"]
pdf-pdfium = ["dep:pdfium-render"]
markdown = ["dep:pulldown-cmark", "dep:unicode-width", "svg"]

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
strip = true
